# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/runtime-7.14.8" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.14.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.14.8.tgz";
        sha512 = "twj3L8Og5SaCRCErB4x4ajbvBIVV77CGeFglHpeg5WC5FF8TZzBWXtTJ4MqaD9QszLYTtr+IsaAL2rEUevb+eg==";
      };
    };
    "@babel/runtime-corejs3-7.14.9" = {
      name = "_at_babel_slash_runtime-corejs3";
      packageName = "@babel/runtime-corejs3";
      version = "7.14.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime-corejs3/-/runtime-corejs3-7.14.9.tgz";
        sha512 = "64RiH2ON4/y8qYtoa8rUiyam/tUVyGqRyNYhe+vCRGmjnV4bUlZvY+mwd0RrmLoCpJpdq3RsrNqKb7SJdw/4kw==";
      };
    };
    "@panter/vue-i18next-0.15.2" = {
      name = "_at_panter_slash_vue-i18next";
      packageName = "@panter/vue-i18next";
      version = "0.15.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@panter/vue-i18next/-/vue-i18next-0.15.2.tgz";
        sha512 = "7VX9GyxHJNEJKa2CRzC294Oz5EEbzVDZ1o3O/P8gL/PWBmcFOFsuivRbP/1a9ga2ihv/NBzoCWMCNIEEeCcONQ==";
      };
    };
    "ajv-6.12.6" = {
      name = "ajv";
      packageName = "ajv";
      version = "6.12.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-6.12.6.tgz";
        sha512 = "j3fVLgvTo527anyYyJOGTYJbG+vnnQYvE0m5mmkc1TK+nxAppkCLMIL0aZ4dblVCNoGShhm+kzE4ZUykBoMg4g==";
      };
    };
    "ajv-keywords-3.5.2" = {
      name = "ajv-keywords";
      packageName = "ajv-keywords";
      version = "3.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv-keywords/-/ajv-keywords-3.5.2.tgz";
        sha512 = "5p6WTN0DdTGVQk6VjcEju19IgaHudalcfabD7yhDGeA6bcQnmL+CpveLJq/3hvfwd1aof6L386Ougkx6RfyMIQ==";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "available-typed-arrays-1.0.4" = {
      name = "available-typed-arrays";
      packageName = "available-typed-arrays";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/available-typed-arrays/-/available-typed-arrays-1.0.4.tgz";
        sha512 = "SA5mXJWrId1TaQjfxUYghbqQ/hYioKmLJvPJyDuYRtXXenFNMjj4hSSt1Cf1xsuXSXrtxrVC5Ot4eU6cOtBDdA==";
      };
    };
    "babel-code-frame-6.26.0" = {
      name = "babel-code-frame";
      packageName = "babel-code-frame";
      version = "6.26.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/babel-code-frame/-/babel-code-frame-6.26.0.tgz";
        sha1 = "63fd43f7dc1e3bb7ce35947db8fe369a3f58c74b";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "big.js-5.2.2" = {
      name = "big.js";
      packageName = "big.js";
      version = "5.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/big.js/-/big.js-5.2.2.tgz";
        sha512 = "vyL2OymJxmarO8gxMr0mhChsO9QGwhynfuu4+MHTAW6czfq9humCB7rKpUjDd9YUiDPU4mzpyupFSvOClAwbmQ==";
      };
    };
    "bluebird-3.7.2" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.7.2.tgz";
        sha512 = "XpNj6GDQzdfW+r2Wnn7xiSAd7TM3jzkxGXBGTtWKuSXv1xUV+azxAm8jdWZN06QTQk+2N2XB9jRDkvbmQmcRtg==";
      };
    };
    "buffer-6.0.3" = {
      name = "buffer";
      packageName = "buffer";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-6.0.3.tgz";
        sha512 = "FTiCpNxtwiZZHEZbcbTIcZjERVICn9yq/pDFkTl95/AxzD1naBctN7YO68riM/gLSDY7sdrMby8hofADYuuqOA==";
      };
    };
    "call-bind-1.0.2" = {
      name = "call-bind";
      packageName = "call-bind";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/call-bind/-/call-bind-1.0.2.tgz";
        sha512 = "7O+FbCihrB5WGbFYesctwmTKae6rOiIzmz1icreWJ+0aA7LJfuqhEso2T9ncpcFtzMQtzXf2QGGueWJGTYsqrA==";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "clone-2.1.2" = {
      name = "clone";
      packageName = "clone";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-2.1.2.tgz";
        sha1 = "1b7f4b9f591f1e8f83670401600345a02887435f";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha1 = "a7d0558bd89c42f795dd42328f740831ca53bc25";
      };
    };
    "commander-2.20.3" = {
      name = "commander";
      packageName = "commander";
      version = "2.20.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.20.3.tgz";
        sha512 = "GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==";
      };
    };
    "compare-versions-3.6.0" = {
      name = "compare-versions";
      packageName = "compare-versions";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/compare-versions/-/compare-versions-3.6.0.tgz";
        sha512 = "W6Af2Iw1z4CB7q4uU4hv646dW9GQuBM+YpC0UvUCWSD8w90SJjp+ujJuXaEMtAXBtSqGfMPuFOVn4/+FlaqfBA==";
      };
    };
    "core-js-3.16.0" = {
      name = "core-js";
      packageName = "core-js";
      version = "3.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-3.16.0.tgz";
        sha512 = "5+5VxRFmSf97nM8Jr2wzOwLqRo6zphH2aX+7KsAUONObyzakDNq2G/bgbhinxB4PoV9L3aXQYhiDKyIKWd2c8g==";
      };
    };
    "core-js-pure-3.16.0" = {
      name = "core-js-pure";
      packageName = "core-js-pure";
      version = "3.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js-pure/-/core-js-pure-3.16.0.tgz";
        sha512 = "wzlhZNepF/QA9yvx3ePDgNGudU5KDB8lu/TRPKelYA/QtSnkS/cLl2W+TIdEX1FAFcBr0YpY7tPDlcmXJ7AyiQ==";
      };
    };
    "css-loader-1.0.1" = {
      name = "css-loader";
      packageName = "css-loader";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-loader/-/css-loader-1.0.1.tgz";
        sha512 = "+ZHAZm/yqvJ2kDtPne3uX0C+Vr3Zn5jFn2N4HywtS5ujwvsVkyg0VArEXpl3BgczDA8anieki1FIzhchX4yrDw==";
      };
    };
    "css-selector-tokenizer-0.7.3" = {
      name = "css-selector-tokenizer";
      packageName = "css-selector-tokenizer";
      version = "0.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-selector-tokenizer/-/css-selector-tokenizer-0.7.3.tgz";
        sha512 = "jWQv3oCEL5kMErj4wRnK/OPoBi0D+P1FR2cDCKYPaMeD2eW3/mttav8HT4hT1CKopiJI/psEULjkClhvJo4Lvg==";
      };
    };
    "css-vars-ponyfill-2.4.6" = {
      name = "css-vars-ponyfill";
      packageName = "css-vars-ponyfill";
      version = "2.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-vars-ponyfill/-/css-vars-ponyfill-2.4.6.tgz";
        sha512 = "FqUFzMlI5jpPl73R9FrUuittWM/t7RDEnyp0603MCNEy6PI/1PALIX1d15cui6UAN/V8tnIWZDMz6WoZD87eGQ==";
      };
    };
    "cssesc-3.0.0" = {
      name = "cssesc";
      packageName = "cssesc";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cssesc/-/cssesc-3.0.0.tgz";
        sha512 = "/Tb/JcjK111nNScGob5MNtsntNM1aCNUDipB/TkwZFhyDrrE47SOx/18wF2bbjgc3ZzCSKW1T5nt5EbFoAz/Vg==";
      };
    };
    "d-1.0.1" = {
      name = "d";
      packageName = "d";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d/-/d-1.0.1.tgz";
        sha512 = "m62ShEObQ39CfralilEQRjH6oAMtNCV1xJyEx5LpRYUVN+EviphDgUc/F3hnYbADmkiNs67Y+3ylmlG7Lnu+FA==";
      };
    };
    "deepmerge-2.2.1" = {
      name = "deepmerge";
      packageName = "deepmerge";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deepmerge/-/deepmerge-2.2.1.tgz";
        sha512 = "R9hc1Xa/NOBi9WRVUWg19rl1UB7Tt4kuPd+thNJgFZoxXsTz7ncaPaeIm+40oSGuP33DfMb4sZt1QIGiJzC4EA==";
      };
    };
    "define-properties-1.1.3" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.1.3.tgz";
        sha512 = "3MqfYKj2lLzdMSf8ZIZE/V+Zuy+BgD6f164e8K2w7dgnpKArBDerGYpM46IYYcjnkdPNMjPk9A6VFB8+3SKlXQ==";
      };
    };
    "dom-serializer-1.3.2" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-1.3.2.tgz";
        sha512 = "5c54Bk5Dw4qAxNOI1pFEizPSjVsx5+bpJKmL2kPn8JhBUq2q09tTCa3mjijun2NfK78NMouDYNMBkOrPZiS+ig==";
      };
    };
    "dom-walk-0.1.2" = {
      name = "dom-walk";
      packageName = "dom-walk";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-walk/-/dom-walk-0.1.2.tgz";
        sha512 = "6QvTW9mrGeIegrFXdtQi9pk7O/nSK6lSdXW2eqUspN5LWD7UTji2Fqw5V2YLjBpHEoU9Xl/eUWNpDeZvoyOv2w==";
      };
    };
    "domelementtype-2.2.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.2.0.tgz";
        sha512 = "DtBMo82pv1dFtUmHyr48beiuq792Sxohr+8Hm9zoxklYPfa6n0Z3Byjj2IV7bmr2IyqClnqEQhfgHJJ5QF0R5A==";
      };
    };
    "domhandler-3.3.0" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-3.3.0.tgz";
        sha512 = "J1C5rIANUbuYK+FuFL98650rihynUOEzRLxW+90bKZRWB6A1X1Tf82GxR1qAWLyfNPRvjqfip3Q5tdYlmAa9lA==";
      };
    };
    "domhandler-4.2.0" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-4.2.0.tgz";
        sha512 = "zk7sgt970kzPks2Bf+dwT/PLzghLnsivb9CcxkvR8Mzr66Olr0Ofd8neSbglHJHaHa2MadfoSdNlKYAaafmWfA==";
      };
    };
    "domutils-2.7.0" = {
      name = "domutils";
      packageName = "domutils";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-2.7.0.tgz";
        sha512 = "8eaHa17IwJUPAiB+SoTYBo5mCdeMgdcAoXJ59m6DT1vw+5iLS3gNoqYaRowaBKtGVrOF1Jz4yDTgYKLK2kvfJg==";
      };
    };
    "emojis-list-3.0.0" = {
      name = "emojis-list";
      packageName = "emojis-list";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emojis-list/-/emojis-list-3.0.0.tgz";
        sha512 = "/kyM18EfinwXZbno9FyUGeFh87KC8HRQBQGildHZbEuRyWFOmv1U10o9BBp8XVZDVNNuQKyIGIu5ZYAAXJ0V2Q==";
      };
    };
    "encoding-0.1.13" = {
      name = "encoding";
      packageName = "encoding";
      version = "0.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding/-/encoding-0.1.13.tgz";
        sha512 = "ETBauow1T35Y/WZMkio9jiM0Z5xjHHmJ4XmjZOq1l/dXz3lr2sRn87nJy20RupqSh1F2m3HHPSp8ShIPQJrJ3A==";
      };
    };
    "entities-2.2.0" = {
      name = "entities";
      packageName = "entities";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-2.2.0.tgz";
        sha512 = "p92if5Nz619I0w+akJrLZH0MX0Pb5DX39XOwQTtXSdQQOaYH03S1uIQp4mhOZtAXrxq4ViO67YTiLBo2638o9A==";
      };
    };
    "es-abstract-1.18.5" = {
      name = "es-abstract";
      packageName = "es-abstract";
      version = "1.18.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-abstract/-/es-abstract-1.18.5.tgz";
        sha512 = "DDggyJLoS91CkJjgauM5c0yZMjiD1uK3KcaCeAmffGwZ+ODWzOkPN4QwRbsK5DOFf06fywmyLci3ZD8jLGhVYA==";
      };
    };
    "es-to-primitive-1.2.1" = {
      name = "es-to-primitive";
      packageName = "es-to-primitive";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.1.tgz";
        sha512 = "QCOllgZJtaUo9miYBcLChTUaHNjJF3PYs1VidD7AwiEj1kYxKeQTctLAezAOH5ZKRH0g2IgPn6KwB4IT8iRpvA==";
      };
    };
    "es5-ext-0.10.53" = {
      name = "es5-ext";
      packageName = "es5-ext";
      version = "0.10.53";
      src = fetchurl {
        url = "https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.53.tgz";
        sha512 = "Xs2Stw6NiNHWypzRTY1MtaG/uJlwCk8kH81920ma8mvN8Xq1gsfhZvpkImLQArw8AHnv8MT2I45J3c0R8slE+Q==";
      };
    };
    "es6-iterator-2.0.3" = {
      name = "es6-iterator";
      packageName = "es6-iterator";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-iterator/-/es6-iterator-2.0.3.tgz";
        sha1 = "a7de889141a05a94b0854403b2d0a0fbfa98f3b7";
      };
    };
    "es6-symbol-3.1.3" = {
      name = "es6-symbol";
      packageName = "es6-symbol";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-symbol/-/es6-symbol-3.1.3.tgz";
        sha512 = "NJ6Yn3FuDinBaBRWl/q5X/s4koRHBrgKAu+yGI6JCBeiu3qrcbJhwT2GeR/EXVfylRk8dpQVJoLEFhK+Mu31NA==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "esutils-2.0.3" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.3.tgz";
        sha512 = "kVscqXk4OCp68SZ0dkgEKVi6/8ij300KBWTJq32P/dYeWTSwK41WyTxalN1eRmA5Z9UU/LX9D7FWSmV9SAYx6g==";
      };
    };
    "event-emitter-0.3.5" = {
      name = "event-emitter";
      packageName = "event-emitter";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-emitter/-/event-emitter-0.3.5.tgz";
        sha1 = "df8c69eef1647923c7157b9ce83840610b02cc39";
      };
    };
    "eventemitter3-4.0.7" = {
      name = "eventemitter3";
      packageName = "eventemitter3";
      version = "4.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter3/-/eventemitter3-4.0.7.tgz";
        sha512 = "8guHBZCwKnFhYdHr2ysuRWErTwhoN2X8XELRlrRwpmfeY2jjuUN4taQMsULKUVo1K4DvZl+0pgfyoysHxvmvEw==";
      };
    };
    "ext-1.4.0" = {
      name = "ext";
      packageName = "ext";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ext/-/ext-1.4.0.tgz";
        sha512 = "Key5NIsUxdqKg3vIsdw9dSuXpPCQ297y6wBjL30edxwPgt2E44WcWBZey/ZvUc6sERLTxKdyCu4gZFmUbk1Q7A==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fast-json-stable-stringify-2.1.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz";
        sha512 = "lhd/wF+Lk98HZoTCtlVraHtfh5XYijIjalXck7saUtuanSDyLMxnHhSXEDJqHxD7msR8D0uCmqlkwjCV8xvwHw==";
      };
    };
    "fast-text-encoding-1.0.3" = {
      name = "fast-text-encoding";
      packageName = "fast-text-encoding";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-text-encoding/-/fast-text-encoding-1.0.3.tgz";
        sha512 = "dtm4QZH9nZtcDt8qJiOH9fcQd1NAgi+K1O2DbE6GG1PPCK/BWfOH3idCTRQ4ImXRUOyopDEgDEnVEE7Y/2Wrig==";
      };
    };
    "fastparse-1.1.2" = {
      name = "fastparse";
      packageName = "fastparse";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastparse/-/fastparse-1.1.2.tgz";
        sha512 = "483XLLxTVIwWK3QTrMGRqUfUpoOs/0hbQrl2oz4J0pAcm3A3bu84wxTFqGqkJzewCLdME38xJLJAxBABfQT8sQ==";
      };
    };
    "font-awesome-4.7.0" = {
      name = "font-awesome";
      packageName = "font-awesome";
      version = "4.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/font-awesome/-/font-awesome-4.7.0.tgz";
        sha1 = "8fa8cf0411a1a31afd07b06d2902bb9fc815a133";
      };
    };
    "font-awesome-webpack-4-1.0.0" = {
      name = "font-awesome-webpack-4";
      packageName = "font-awesome-webpack-4";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/font-awesome-webpack-4/-/font-awesome-webpack-4-1.0.0.tgz";
        sha512 = "FNuIzxr5fYRpkXTU/9SseqizEr6tZwIIOb+VNg037WZe0dDkbLejEwz0S6WSGGcLKpIMF0SI7Ec7yXNu1j4R1w==";
      };
    };
    "foreach-2.0.5" = {
      name = "foreach";
      packageName = "foreach";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/foreach/-/foreach-2.0.5.tgz";
        sha1 = "0bee005018aeb260d0a3af3ae658dd0136ec1b99";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "get-css-data-2.0.2" = {
      name = "get-css-data";
      packageName = "get-css-data";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-css-data/-/get-css-data-2.0.2.tgz";
        sha512 = "pYqg80/7u/MdBrrAQj2OIoZ08TxEnvCHyU5WFnPxxS/D0S8OpUTkqGFRzn8bO38DmtCuYBpR9VMCen78BL4jiQ==";
      };
    };
    "get-intrinsic-1.1.1" = {
      name = "get-intrinsic";
      packageName = "get-intrinsic";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-intrinsic/-/get-intrinsic-1.1.1.tgz";
        sha512 = "kWZrnVM42QCiEA2Ig1bG8zjoIMOgxWwYCEeNdwY6Tv/cOSeGpcoX4pXHfKUxNKVoArnrEr2e9srnAxxGIraS9Q==";
      };
    };
    "gettext-parser-3.1.1" = {
      name = "gettext-parser";
      packageName = "gettext-parser";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/gettext-parser/-/gettext-parser-3.1.1.tgz";
        sha512 = "vNhWcqXEtZPs5Ft1ReA34g7ByWotpcOIeJvXVy2jF3/G2U9v6W0wG4Z4hXzcU8R//jArqkgHcVCGgGqa4vxVlQ==";
      };
    };
    "global-4.4.0" = {
      name = "global";
      packageName = "global";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/global/-/global-4.4.0.tgz";
        sha512 = "wv/LAoHdRE3BeTGz53FAamhGlPLhlssK45usmGFThIi4XqnBmjKQ16u+RNbP7WvigRZDxUsM0J3gcQ5yicaL0w==";
      };
    };
    "grapheme-splitter-1.0.4" = {
      name = "grapheme-splitter";
      packageName = "grapheme-splitter";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/grapheme-splitter/-/grapheme-splitter-1.0.4.tgz";
        sha512 = "bzh50DW9kTPM00T8y4o8vQg89Di9oLJVLW/KaOGIXJWP/iqCN6WKYkbNOF04vFLJhwcpYUh9ydh/+5vpOqV4YQ==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "has-bigints-1.0.1" = {
      name = "has-bigints";
      packageName = "has-bigints";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-bigints/-/has-bigints-1.0.1.tgz";
        sha512 = "LSBS2LjbNBTf6287JEbEzvJgftkF5qFkmCo9hDRpAzKhUOlJ+hx8dd4USs00SgsUNwc4617J9ki5YtEClM2ffA==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha1 = "b5d454dc2199ae225699f3467e5a07f3b955bafd";
      };
    };
    "has-symbols-1.0.2" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.2.tgz";
        sha512 = "chXa79rL/UC2KlX17jo3vRGz0azaWEx5tGqZg5pO3NUyEJVB17dMruQlzCCOfUvElghKcm5194+BCRvi2Rv/Gw==";
      };
    };
    "htmlparser2-4.1.0" = {
      name = "htmlparser2";
      packageName = "htmlparser2";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/htmlparser2/-/htmlparser2-4.1.0.tgz";
        sha512 = "4zDq1a1zhE4gQso/c5LP1OtrhYTncXNSpvJYtWJBtXAETPlMfi3IFNjGuQbYLuVY4ZR0QMqRVvo4Pdy9KLyP8Q==";
      };
    };
    "i18next-19.9.2" = {
      name = "i18next";
      packageName = "i18next";
      version = "19.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/i18next/-/i18next-19.9.2.tgz";
        sha512 = "0i6cuo6ER6usEOtKajUUDj92zlG+KArFia0857xxiEHAQcUwh/RtOQocui1LPJwunSYT574Pk64aNva1kwtxZg==";
      };
    };
    "i18next-conv-9.2.1" = {
      name = "i18next-conv";
      packageName = "i18next-conv";
      version = "9.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/i18next-conv/-/i18next-conv-9.2.1.tgz";
        sha512 = "RAlQIIf5BFfEywqd/1R9W4S3bGL+6qMKD/HKfnSisw9K5tSx4chQKf6pbBNzMyaoTBqWy+ZHS27ZmxE5GIGgag==";
      };
    };
    "i18next-xhr-backend-3.2.2" = {
      name = "i18next-xhr-backend";
      packageName = "i18next-xhr-backend";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/i18next-xhr-backend/-/i18next-xhr-backend-3.2.2.tgz";
        sha512 = "OtRf2Vo3IqAxsttQbpjYnmMML12IMB5e0fc5B7qKJFLScitYaXa1OhMX0n0X/3vrfFlpHL9Ro/H+ps4Ej2j7QQ==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "icss-replace-symbols-1.1.0" = {
      name = "icss-replace-symbols";
      packageName = "icss-replace-symbols";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/icss-replace-symbols/-/icss-replace-symbols-1.1.0.tgz";
        sha1 = "06ea6f83679a7749e386cfe1fe812ae5db223ded";
      };
    };
    "icss-utils-2.1.0" = {
      name = "icss-utils";
      packageName = "icss-utils";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/icss-utils/-/icss-utils-2.1.0.tgz";
        sha1 = "83f0a0ec378bf3246178b6c2ad9136f135b1c962";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "internal-slot-1.0.3" = {
      name = "internal-slot";
      packageName = "internal-slot";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/internal-slot/-/internal-slot-1.0.3.tgz";
        sha512 = "O0DB1JC/sPyZl7cIo78n5dR7eUSwwpYPiXRhTzNxZVAMUuB8vlnRFyLxdrVToks6XPLVnFfbzaVd5WLjhgg+vA==";
      };
    };
    "intersection-observer-0.7.0" = {
      name = "intersection-observer";
      packageName = "intersection-observer";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/intersection-observer/-/intersection-observer-0.7.0.tgz";
        sha512 = "Id0Fij0HsB/vKWGeBe9PxeY45ttRiBmhFyyt/geBdDHBYNctMRTE3dC1U3ujzz3lap+hVXlEcVaB56kZP/eEUg==";
      };
    };
    "ip-1.1.5" = {
      name = "ip";
      packageName = "ip";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip/-/ip-1.1.5.tgz";
        sha1 = "bdded70114290828c0a039e72ef25f5aaec4354a";
      };
    };
    "ip-regex-4.3.0" = {
      name = "ip-regex";
      packageName = "ip-regex";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip-regex/-/ip-regex-4.3.0.tgz";
        sha512 = "B9ZWJxHHOHUhUjCPrMpLD4xEq35bUTClHM1S6CBU5ixQnkZmwipwgc96vAd7AAGM9TGHvJR+Uss+/Ak6UphK+Q==";
      };
    };
    "irc-framework-4.11.0" = {
      name = "irc-framework";
      packageName = "irc-framework";
      version = "4.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/irc-framework/-/irc-framework-4.11.0.tgz";
        sha512 = "A7AoNxAGzViARQv4sVchmTzRiWiQZMCuQVnCOhrggEgAMsc8Vr345U5/JMN5I45gqL4LVfjtruWokp5YiU23Iw==";
      };
    };
    "is-arguments-1.1.0" = {
      name = "is-arguments";
      packageName = "is-arguments";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arguments/-/is-arguments-1.1.0.tgz";
        sha512 = "1Ij4lOMPl/xB5kBDn7I+b2ttPMKa8szhEIrXDuXQD/oe3HJLTLhqhgGspwgyGd6MOywBUqVvYicF72lkgDnIHg==";
      };
    };
    "is-bigint-1.0.2" = {
      name = "is-bigint";
      packageName = "is-bigint";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-bigint/-/is-bigint-1.0.2.tgz";
        sha512 = "0JV5+SOCQkIdzjBK9buARcV804Ddu7A0Qet6sHi3FimE9ne6m4BGQZfRn+NZiXbBk4F4XmHfDZIipLj9pX8dSA==";
      };
    };
    "is-boolean-object-1.1.1" = {
      name = "is-boolean-object";
      packageName = "is-boolean-object";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-boolean-object/-/is-boolean-object-1.1.1.tgz";
        sha512 = "bXdQWkECBUIAcCkeH1unwJLIpZYaa5VvuygSyS/c2lf719mTKZDU5UdDRlpd01UjADgmW8RfqaP+mRaVPdr/Ng==";
      };
    };
    "is-callable-1.2.3" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.2.3.tgz";
        sha512 = "J1DcMe8UYTBSrKezuIUTUwjXsho29693unXM2YhJUTR2txK/eG47bvNa/wipPFmZFgr/N6f1GA66dv0mEyTIyQ==";
      };
    };
    "is-date-object-1.0.4" = {
      name = "is-date-object";
      packageName = "is-date-object";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.4.tgz";
        sha512 = "/b4ZVsG7Z5XVtIxs/h9W8nvfLgSAyKYdtGWQLbqy6jA1icmgjf8WCoTKgeS4wy5tYaPePouzFMANbnj94c2Z+A==";
      };
    };
    "is-function-1.0.2" = {
      name = "is-function";
      packageName = "is-function";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-function/-/is-function-1.0.2.tgz";
        sha512 = "lw7DUp0aWXYg+CBCN+JKkcE0Q2RayZnSvnZBlwgxHBQhqt5pZNVy4Ri7H9GmmXkdu7LUthszM+Tor1u/2iBcpQ==";
      };
    };
    "is-generator-function-1.0.9" = {
      name = "is-generator-function";
      packageName = "is-generator-function";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-generator-function/-/is-generator-function-1.0.9.tgz";
        sha512 = "ZJ34p1uvIfptHCN7sFTjGibB9/oBg17sHqzDLfuwhvmN/qLVvIQXRQ8licZQ35WJ8KuEQt/etnnzQFI9C9Ue/A==";
      };
    };
    "is-negative-zero-2.0.1" = {
      name = "is-negative-zero";
      packageName = "is-negative-zero";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-negative-zero/-/is-negative-zero-2.0.1.tgz";
        sha512 = "2z6JzQvZRa9A2Y7xC6dQQm4FSTSTNWjKIYYTt4246eMTJmIo0Q+ZyOsU66X8lxK1AbB92dFeglPLrhwpeRKO6w==";
      };
    };
    "is-number-object-1.0.5" = {
      name = "is-number-object";
      packageName = "is-number-object";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number-object/-/is-number-object-1.0.5.tgz";
        sha512 = "RU0lI/n95pMoUKu9v1BZP5MBcZuNSVJkMkAG2dJqC4z2GlkGUNeH68SuHuBKBD/XFe+LHZ+f9BKkLET60Niedw==";
      };
    };
    "is-regex-1.1.3" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.1.3.tgz";
        sha512 = "qSVXFz28HM7y+IWX6vLCsexdlvzT1PJNFSBuaQLQ5o0IEw8UDYW6/2+eCMVyIsbM8CNLX2a/QWmSpyxYEHY7CQ==";
      };
    };
    "is-string-1.0.6" = {
      name = "is-string";
      packageName = "is-string";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-string/-/is-string-1.0.6.tgz";
        sha512 = "2gdzbKUuqtQ3lYNrUTQYoClPhm7oQu4UdpSZMp1/DGgkHBT8E2Z1l0yMdb6D4zNAxwDiMv8MdulKROJGNl0Q0w==";
      };
    };
    "is-symbol-1.0.4" = {
      name = "is-symbol";
      packageName = "is-symbol";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.4.tgz";
        sha512 = "C/CPBqKWnvdcxqIARxyOh4v1UUEOCHpgDa0WYgpKDFMszcrPcffg5uhwSgPCLD2WWxmq6isisz87tzT01tuGhg==";
      };
    };
    "is-typed-array-1.1.5" = {
      name = "is-typed-array";
      packageName = "is-typed-array";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typed-array/-/is-typed-array-1.1.5.tgz";
        sha512 = "S+GRDgJlR3PyEbsX/Fobd9cqpZBuvUS+8asRqYDMLCb2qMzt1oz5m5oxQCxOgUDxiWsOVNi4yaF+/uvdlHlYug==";
      };
    };
    "isomorphic-textencoder-1.0.1" = {
      name = "isomorphic-textencoder";
      packageName = "isomorphic-textencoder";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isomorphic-textencoder/-/isomorphic-textencoder-1.0.1.tgz";
        sha512 = "676hESgHullDdHDsj469hr+7t3i/neBKU9J7q1T4RHaWwLAsaQnywC0D1dIUId0YZ+JtVrShzuBk1soo0+GVcQ==";
      };
    };
    "js-tokens-3.0.2" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-3.0.2.tgz";
        sha1 = "9866df395102130e38f7f996bceb65443209c25b";
      };
    };
    "json-schema-traverse-0.4.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.4.1.tgz";
        sha512 = "xbbCH5dCYU5T8LcEhhuh7HJ88HXuW3qsI3Y0zOZFKfZEHcpWiHU/Jxzk629Brsab/mMiHQti9wMP+845RPe3Vg==";
      };
    };
    "json5-1.0.1" = {
      name = "json5";
      packageName = "json5";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-1.0.1.tgz";
        sha512 = "aKS4WQjPenRxiQsC93MNfjx+nbF4PAdYzmd/1JIj8HYzqfbu86beTuNgXDzPknWk0n0uARlyewZo4s++ES36Ow==";
      };
    };
    "json5-2.2.0" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.0.tgz";
        sha512 = "f+8cldu7X/y7RAJurMEJmdoKXGB/X550w2Nr3tTbezL6RwEE/iMcm+tZnXeoZtKuOq6ft8+CqzEkrIgx1fPoQA==";
      };
    };
    "less-loader-4.1.0" = {
      name = "less-loader";
      packageName = "less-loader";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/less-loader/-/less-loader-4.1.0.tgz";
        sha512 = "KNTsgCE9tMOM70+ddxp9yyt9iHqgmSs0yTZc5XH5Wo+g80RWRIYNqE58QJKm/yMud5wZEvz50ugRDuzVIkyahg==";
      };
    };
    "loader-utils-1.4.0" = {
      name = "loader-utils";
      packageName = "loader-utils";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loader-utils/-/loader-utils-1.4.0.tgz";
        sha512 = "qH0WSMBtn/oHuwjy/NucEgbx5dbxxnxup9s4PVXJUDHZBQY+s0NWA9rJf53RBnQZxfch7euUui7hpoAPvALZdA==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lodash.get-4.4.2" = {
      name = "lodash.get";
      packageName = "lodash.get";
      version = "4.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.get/-/lodash.get-4.4.2.tgz";
        sha1 = "2d177f652fa31e939b4438d5341499dfa3825e99";
      };
    };
    "middleware-handler-0.2.0" = {
      name = "middleware-handler";
      packageName = "middleware-handler";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/middleware-handler/-/middleware-handler-0.2.0.tgz";
        sha1 = "bf02af7e6b577c0230609b2ae58df0e446f3fd02";
      };
    };
    "min-document-2.19.0" = {
      name = "min-document";
      packageName = "min-document";
      version = "2.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/min-document/-/min-document-2.19.0.tgz";
        sha1 = "7bd282e3f5842ed295bb748cdd9f1ffa2c824685";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "mkdirp-0.5.5" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.5.tgz";
        sha512 = "NKmAlESf6jMGym1++R0Ra7wvhV+wFW63FaSOFPwRahvea0gMUcGUhVeAg/0BC0wiv9ih5NYPB1Wn1UEI1/L+xQ==";
      };
    };
    "murmurhash3js-3.0.1" = {
      name = "murmurhash3js";
      packageName = "murmurhash3js";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/murmurhash3js/-/murmurhash3js-3.0.1.tgz";
        sha1 = "3e983e5b47c2a06f43a713174e7e435ca044b998";
      };
    };
    "next-tick-1.0.0" = {
      name = "next-tick";
      packageName = "next-tick";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/next-tick/-/next-tick-1.0.0.tgz";
        sha1 = "ca86d1fe8828169b0120208e3dc8424b9db8342c";
      };
    };
    "node-gettext-2.1.0" = {
      name = "node-gettext";
      packageName = "node-gettext";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gettext/-/node-gettext-2.1.0.tgz";
        sha512 = "vsHImHl+Py0vB7M2UXcFEJ5NJ3950gcja45YclBFtYxYeZiqdfQdcu+G9s4L7jpRFSh/J/7VoS3upR4JM1nS+g==";
      };
    };
    "object-inspect-1.11.0" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.11.0.tgz";
        sha512 = "jp7ikS6Sd3GxQfZJPyH3cjcbJF6GZPClgdV+EFygjFLQ5FmW/dRUnTd9PQ9k0JhoNDabWFbpF1yCdSWCC6gexg==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object.assign-4.1.2" = {
      name = "object.assign";
      packageName = "object.assign";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.assign/-/object.assign-4.1.2.tgz";
        sha512 = "ixT2L5THXsApyiUPYKmW+2EHpXXe5Ii3M+f4e+aJFAHao5amFRW6J0OO6c/LU8Be47utCx2GL89hxGB6XSmKuQ==";
      };
    };
    "parse-headers-2.0.3" = {
      name = "parse-headers";
      packageName = "parse-headers";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-headers/-/parse-headers-2.0.3.tgz";
        sha512 = "QhhZ+DCCit2Coi2vmAKbq5RGTRcQUOE2+REgv8vdyu7MnYx2eZztegqtTx99TZ86GTIwqiy3+4nQTWZ2tgmdCA==";
      };
    };
    "pify-3.0.0" = {
      name = "pify";
      packageName = "pify";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pify/-/pify-3.0.0.tgz";
        sha1 = "e5a4acd2c101fdf3d9a4d07f0dbc4db49dd28176";
      };
    };
    "postcss-6.0.23" = {
      name = "postcss";
      packageName = "postcss";
      version = "6.0.23";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss/-/postcss-6.0.23.tgz";
        sha512 = "soOk1h6J3VMTZtVeVpv15/Hpdl2cBLX3CAw4TAbkpTJiNPk9YP/zWcD1ND+xEtvyuuvKzbxliTOIyvkSeSJ6ag==";
      };
    };
    "postcss-modules-extract-imports-1.2.1" = {
      name = "postcss-modules-extract-imports";
      packageName = "postcss-modules-extract-imports";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-extract-imports/-/postcss-modules-extract-imports-1.2.1.tgz";
        sha512 = "6jt9XZwUhwmRUhb/CkyJY020PYaPJsCyt3UjbaWo6XEbH/94Hmv6MP7fG2C5NDU/BcHzyGYxNtHvM+LTf9HrYw==";
      };
    };
    "postcss-modules-local-by-default-1.2.0" = {
      name = "postcss-modules-local-by-default";
      packageName = "postcss-modules-local-by-default";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-local-by-default/-/postcss-modules-local-by-default-1.2.0.tgz";
        sha1 = "f7d80c398c5a393fa7964466bd19500a7d61c069";
      };
    };
    "postcss-modules-scope-1.1.0" = {
      name = "postcss-modules-scope";
      packageName = "postcss-modules-scope";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-scope/-/postcss-modules-scope-1.1.0.tgz";
        sha1 = "d6ea64994c79f97b62a72b426fbe6056a194bb90";
      };
    };
    "postcss-modules-values-1.3.0" = {
      name = "postcss-modules-values";
      packageName = "postcss-modules-values";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-modules-values/-/postcss-modules-values-1.3.0.tgz";
        sha1 = "ecffa9d7e192518389f42ad0e83f72aec456ea20";
      };
    };
    "postcss-value-parser-3.3.1" = {
      name = "postcss-value-parser";
      packageName = "postcss-value-parser";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/postcss-value-parser/-/postcss-value-parser-3.3.1.tgz";
        sha512 = "pISE66AbVkp4fDQ7VHBwRNXzAAKJjw4Vw7nWI/+Q3vuly7SNfgYXvm6i5IgFylHGK5sP/xHAbB7N49OS4gWNyQ==";
      };
    };
    "process-0.11.10" = {
      name = "process";
      packageName = "process";
      version = "0.11.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.11.10.tgz";
        sha1 = "7332300e840161bda3e69a1d1d91a7d4bc16f182";
      };
    };
    "punycode-2.1.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.1.1.tgz";
        sha512 = "XRsRjdf+j5ml+y/6GKHPZbrF/8p2Yga0JPtdqTIY2Xe5ohJPD9saDJJLPvp9+NSBprVvevdXZybnj2cv8OEd0A==";
      };
    };
    "readable-stream-3.6.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "3.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-3.6.0.tgz";
        sha512 = "BViHy7LKeTz4oNnkcLJ+lVSL6vpiFeX6/d3oSH8zCW7UxP2onchk+vTGB143xuFjHS3deTgkKoXXymXqymiIdA==";
      };
    };
    "regenerator-runtime-0.13.9" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.9.tgz";
        sha512 = "p3VT+cOEgxFsRRA9X4lkI1E+k2/CtnKtU4gcxyaCUreilL/vqI6CdZ3wxVUx3UOUg+gnUOQQcRI7BmSI656MYA==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "schema-utils-0.4.7" = {
      name = "schema-utils";
      packageName = "schema-utils";
      version = "0.4.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/schema-utils/-/schema-utils-0.4.7.tgz";
        sha512 = "v/iwU6wvwGK8HbU9yi3/nhGzP0yGSuhQMzL6ySiec1FSrZZDkhm4noOSWzrNFo/jEc+SJY6jRTwuwbSXJPDUnQ==";
      };
    };
    "scrollparent-2.0.1" = {
      name = "scrollparent";
      packageName = "scrollparent";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/scrollparent/-/scrollparent-2.0.1.tgz";
        sha1 = "715d5b9cc57760fb22bdccc3befb5bfe06b1a317";
      };
    };
    "side-channel-1.0.4" = {
      name = "side-channel";
      packageName = "side-channel";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/side-channel/-/side-channel-1.0.4.tgz";
        sha512 = "q5XPytqFEIKHkGdiMIrY10mvLRvnQh42/+GoBlFW3b2LXLE2xxJpZFdm94we0BaoV3RwJyGqg5wS7epxTv0Zvw==";
      };
    };
    "smart-buffer-4.1.0" = {
      name = "smart-buffer";
      packageName = "smart-buffer";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/smart-buffer/-/smart-buffer-4.1.0.tgz";
        sha512 = "iVICrxOzCynf/SNaBQCw34eM9jROU/s5rzIhpOvzhzuYHfJR/DhZfDkXiZSgKXfgv26HT3Yni3AV/DGw0cGnnw==";
      };
    };
    "socks-2.6.1" = {
      name = "socks";
      packageName = "socks";
      version = "2.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/socks/-/socks-2.6.1.tgz";
        sha512 = "kLQ9N5ucj8uIcxrDwjm0Jsqk06xdpBjGNQtpXy4Q8/QY2k+fY7nZH8CARy+hkbG+SGAovmzzuauCpBlb8FrnBA==";
      };
    };
    "source-list-map-2.0.1" = {
      name = "source-list-map";
      packageName = "source-list-map";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-list-map/-/source-list-map-2.0.1.tgz";
        sha512 = "qnQ7gVMxGNxsiL4lEuJwe/To8UnK7fAnmbGEEH8RpLouuKbeEm0lhbQVFIrNSuB+G7tVrAlVsZgETT5nljf+Iw==";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "stream-browserify-3.0.0" = {
      name = "stream-browserify";
      packageName = "stream-browserify";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-browserify/-/stream-browserify-3.0.0.tgz";
        sha512 = "H73RAHsVBapbim0tU2JwwOiXUj+fikfiaoYAKHF3VJfA0pe2BCzkhAHBlLG6REzE+2WNZcxOXjK7lkso+9euLA==";
      };
    };
    "strftime-0.10.0" = {
      name = "strftime";
      packageName = "strftime";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strftime/-/strftime-0.10.0.tgz";
        sha1 = "b3f0fa419295202a5a289f6d6be9f4909a617193";
      };
    };
    "string.prototype.trimend-1.0.4" = {
      name = "string.prototype.trimend";
      packageName = "string.prototype.trimend";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimend/-/string.prototype.trimend-1.0.4.tgz";
        sha512 = "y9xCjw1P23Awk8EvTpcyL2NIr1j7wJ39f+k6lvRnSMz+mz9CGz9NYPelDk42kOz6+ql8xjfK8oYzy3jAP5QU5A==";
      };
    };
    "string.prototype.trimstart-1.0.4" = {
      name = "string.prototype.trimstart";
      packageName = "string.prototype.trimstart";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimstart/-/string.prototype.trimstart-1.0.4.tgz";
        sha512 = "jh6e984OBfvxS50tdY2nRZnoC5/mLFKOREQfw8t5yytkoUsJRNxvI/E39qu1sD0OtWI3OC0XgKSmcWwziwYuZw==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "style-loader-0.22.1" = {
      name = "style-loader";
      packageName = "style-loader";
      version = "0.22.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/style-loader/-/style-loader-0.22.1.tgz";
        sha512 = "WXUrLeinPIR1Oat3PfCDro7qTniwNTJqGqv1KcQiL3JR5PzrVLTyNsd9wTsPXG/qNCJ7lzR2NY/QDjFsP7nuSQ==";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "tinycon-0.6.8" = {
      name = "tinycon";
      packageName = "tinycon";
      version = "0.6.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/tinycon/-/tinycon-0.6.8.tgz";
        sha1 = "e7da223e3ee0cbf9db7963fa335699bb21777a73";
      };
    };
    "type-1.2.0" = {
      name = "type";
      packageName = "type";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type/-/type-1.2.0.tgz";
        sha512 = "+5nt5AAniqsCnu2cEQQdpzCAh33kVx8n0VoFidKpB1dVVLAN/F+bgVOqOJqOnEnrhp222clB5p3vUlD+1QAnfg==";
      };
    };
    "type-2.5.0" = {
      name = "type";
      packageName = "type";
      version = "2.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type/-/type-2.5.0.tgz";
        sha512 = "180WMDQaIMm3+7hGXWf12GtdniDEy7nYcyFMKJn/eZz/6tSLXrUN9V0wKSbMjej0I1WHWbpREDEKHtqPQa9NNw==";
      };
    };
    "unbox-primitive-1.0.1" = {
      name = "unbox-primitive";
      packageName = "unbox-primitive";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unbox-primitive/-/unbox-primitive-1.0.1.tgz";
        sha512 = "tZU/3NqK3dA5gpE1KtyiJUrEB0lxnGkMFHptJ7q6ewdZ8s12QrODwNbhIJStmJkd1QDXa1NRA8aF2A1zk/Ypyw==";
      };
    };
    "uri-js-4.4.1" = {
      name = "uri-js";
      packageName = "uri-js";
      version = "4.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-js/-/uri-js-4.4.1.tgz";
        sha512 = "7rKUyy33Q1yc98pQ1DAmLtwX109F7TIfWlW1Ydo8Wl1ii1SeHieeh0HHfPeL2fMXK6z0s8ecKs9frCuLJvndBg==";
      };
    };
    "util-0.12.4" = {
      name = "util";
      packageName = "util";
      version = "0.12.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/util/-/util-0.12.4.tgz";
        sha512 = "bxZ9qtSlGUWSOy9Qa9Xgk11kSslpuZwaxCg4sNIDj6FLucDab2JxnHwyNTCpHMtK1MjoQiWQ6DiUMZYbSrO+Sw==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "vue-2.6.14" = {
      name = "vue";
      packageName = "vue";
      version = "2.6.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue/-/vue-2.6.14.tgz";
        sha512 = "x2284lgYvjOMj3Za7kqzRcUSxBboHqtgRE2zlos1qWaOye5yUmHn42LB1250NJBLRwEcdrB0JRwyPTEPhfQjiQ==";
      };
    };
    "vue-observe-visibility-0.4.6" = {
      name = "vue-observe-visibility";
      packageName = "vue-observe-visibility";
      version = "0.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue-observe-visibility/-/vue-observe-visibility-0.4.6.tgz";
        sha512 = "xo0CEVdkjSjhJoDdLSvoZoQrw/H2BlzB5jrCBKGZNXN2zdZgMuZ9BKrxXDjNP2AxlcCoKc8OahI3F3r3JGLv2Q==";
      };
    };
    "vue-resize-0.4.5" = {
      name = "vue-resize";
      packageName = "vue-resize";
      version = "0.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue-resize/-/vue-resize-0.4.5.tgz";
        sha512 = "bhP7MlgJQ8TIkZJXAfDf78uJO+mEI3CaLABLjv0WNzr4CcGRGPIAItyWYnP6LsPA4Oq0WE+suidNs6dgpO4RHg==";
      };
    };
    "vue-virtual-scroller-1.0.10" = {
      name = "vue-virtual-scroller";
      packageName = "vue-virtual-scroller";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/vue-virtual-scroller/-/vue-virtual-scroller-1.0.10.tgz";
        sha512 = "Hn4qSBDhRY4XdngPioYy/ykDjrLX/NMm1fQXm/4UQQ/Xv1x8JbHGFZNftQowTcfICgN7yc31AKnUk1UGLJ2ndA==";
      };
    };
    "whatwg-fetch-3.6.2" = {
      name = "whatwg-fetch";
      packageName = "whatwg-fetch";
      version = "3.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-fetch/-/whatwg-fetch-3.6.2.tgz";
        sha512 = "bJlen0FcuU/0EMLrdbJ7zOnW6ITZLrZMIarMUVmdKtsGvZna8vxKYaexICWPfZ8qwf9fzNq+UEIZrnSaApt6RA==";
      };
    };
    "which-boxed-primitive-1.0.2" = {
      name = "which-boxed-primitive";
      packageName = "which-boxed-primitive";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-boxed-primitive/-/which-boxed-primitive-1.0.2.tgz";
        sha512 = "bwZdv0AKLpplFY2KZRX6TvyuN7ojjr7lwkg6ml0roIy9YeuSr7JS372qlNW18UQYzgYK9ziGcerWqZOmEn9VNg==";
      };
    };
    "which-typed-array-1.1.4" = {
      name = "which-typed-array";
      packageName = "which-typed-array";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/which-typed-array/-/which-typed-array-1.1.4.tgz";
        sha512 = "49E0SpUe90cjpoc7BOJwyPHRqSAd12c10Qm2amdEZrJPCY2NDxaW01zHITrem+rnETY3dwrbH3UUrUwagfCYDA==";
      };
    };
    "xhr-2.6.0" = {
      name = "xhr";
      packageName = "xhr";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xhr/-/xhr-2.6.0.tgz";
        sha512 = "/eCGLb5rxjx5e3mF1A7s+pLlR6CGyqWN91fv1JgER5mVWg1MZmlhBvy9kjcsOdRk8RrIujotWyJamfyrp+WIcA==";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
  };
  args = {
    name = "kiwiirc";
    packageName = "kiwiirc";
    version = "1.5.1";
    src = ./.;
    dependencies = [
      sources."@babel/runtime-7.14.8"
      sources."@babel/runtime-corejs3-7.14.9"
      sources."@panter/vue-i18next-0.15.2"
      sources."ajv-6.12.6"
      sources."ajv-keywords-3.5.2"
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."available-typed-arrays-1.0.4"
      sources."babel-code-frame-6.26.0"
      sources."balanced-match-1.0.2"
      sources."base64-js-1.5.1"
      sources."big.js-5.2.2"
      sources."bluebird-3.7.2"
      sources."buffer-6.0.3"
      sources."call-bind-1.0.2"
      sources."chalk-1.1.3"
      sources."clone-2.1.2"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."commander-2.20.3"
      sources."compare-versions-3.6.0"
      sources."core-js-3.16.0"
      sources."core-js-pure-3.16.0"
      sources."css-loader-1.0.1"
      sources."css-selector-tokenizer-0.7.3"
      sources."css-vars-ponyfill-2.4.6"
      sources."cssesc-3.0.0"
      (sources."d-1.0.1" // {
        dependencies = [
          sources."type-1.2.0"
        ];
      })
      sources."deepmerge-2.2.1"
      sources."define-properties-1.1.3"
      (sources."dom-serializer-1.3.2" // {
        dependencies = [
          sources."domhandler-4.2.0"
        ];
      })
      sources."dom-walk-0.1.2"
      sources."domelementtype-2.2.0"
      sources."domhandler-3.3.0"
      (sources."domutils-2.7.0" // {
        dependencies = [
          sources."domhandler-4.2.0"
        ];
      })
      sources."emojis-list-3.0.0"
      sources."encoding-0.1.13"
      sources."entities-2.2.0"
      sources."es-abstract-1.18.5"
      sources."es-to-primitive-1.2.1"
      sources."es5-ext-0.10.53"
      sources."es6-iterator-2.0.3"
      sources."es6-symbol-3.1.3"
      sources."escape-string-regexp-1.0.5"
      sources."esutils-2.0.3"
      sources."event-emitter-0.3.5"
      sources."eventemitter3-4.0.7"
      sources."ext-1.4.0"
      sources."fast-deep-equal-3.1.3"
      sources."fast-json-stable-stringify-2.1.0"
      sources."fast-text-encoding-1.0.3"
      sources."fastparse-1.1.2"
      sources."font-awesome-4.7.0"
      sources."font-awesome-webpack-4-1.0.0"
      sources."foreach-2.0.5"
      sources."function-bind-1.1.1"
      sources."get-css-data-2.0.2"
      sources."get-intrinsic-1.1.1"
      sources."gettext-parser-3.1.1"
      sources."global-4.4.0"
      sources."grapheme-splitter-1.0.4"
      sources."has-1.0.3"
      sources."has-ansi-2.0.0"
      sources."has-bigints-1.0.1"
      sources."has-flag-3.0.0"
      sources."has-symbols-1.0.2"
      sources."htmlparser2-4.1.0"
      sources."i18next-19.9.2"
      (sources."i18next-conv-9.2.1" // {
        dependencies = [
          sources."ansi-styles-3.2.1"
          sources."chalk-2.4.2"
          sources."supports-color-5.5.0"
        ];
      })
      sources."i18next-xhr-backend-3.2.2"
      sources."iconv-lite-0.6.3"
      sources."icss-replace-symbols-1.1.0"
      sources."icss-utils-2.1.0"
      sources."ieee754-1.2.1"
      sources."inherits-2.0.4"
      sources."internal-slot-1.0.3"
      sources."intersection-observer-0.7.0"
      sources."ip-1.1.5"
      sources."ip-regex-4.3.0"
      sources."irc-framework-4.11.0"
      sources."is-arguments-1.1.0"
      sources."is-bigint-1.0.2"
      sources."is-boolean-object-1.1.1"
      sources."is-callable-1.2.3"
      sources."is-date-object-1.0.4"
      sources."is-function-1.0.2"
      sources."is-generator-function-1.0.9"
      sources."is-negative-zero-2.0.1"
      sources."is-number-object-1.0.5"
      sources."is-regex-1.1.3"
      sources."is-string-1.0.6"
      sources."is-symbol-1.0.4"
      sources."is-typed-array-1.1.5"
      sources."isomorphic-textencoder-1.0.1"
      sources."js-tokens-3.0.2"
      sources."json-schema-traverse-0.4.1"
      sources."json5-2.2.0"
      sources."less-loader-4.1.0"
      (sources."loader-utils-1.4.0" // {
        dependencies = [
          sources."json5-1.0.1"
        ];
      })
      sources."lodash-4.17.21"
      sources."lodash.get-4.4.2"
      sources."middleware-handler-0.2.0"
      sources."min-document-2.19.0"
      sources."minimist-1.2.5"
      sources."mkdirp-0.5.5"
      sources."murmurhash3js-3.0.1"
      sources."next-tick-1.0.0"
      sources."node-gettext-2.1.0"
      sources."object-inspect-1.11.0"
      sources."object-keys-1.1.1"
      sources."object.assign-4.1.2"
      sources."parse-headers-2.0.3"
      sources."pify-3.0.0"
      (sources."postcss-6.0.23" // {
        dependencies = [
          sources."ansi-styles-3.2.1"
          sources."chalk-2.4.2"
          sources."supports-color-5.5.0"
        ];
      })
      sources."postcss-modules-extract-imports-1.2.1"
      sources."postcss-modules-local-by-default-1.2.0"
      sources."postcss-modules-scope-1.1.0"
      sources."postcss-modules-values-1.3.0"
      sources."postcss-value-parser-3.3.1"
      sources."process-0.11.10"
      sources."punycode-2.1.1"
      sources."readable-stream-3.6.0"
      sources."regenerator-runtime-0.13.9"
      sources."safe-buffer-5.2.1"
      sources."safer-buffer-2.1.2"
      sources."schema-utils-0.4.7"
      sources."scrollparent-2.0.1"
      sources."side-channel-1.0.4"
      sources."smart-buffer-4.1.0"
      sources."socks-2.6.1"
      sources."source-list-map-2.0.1"
      sources."source-map-0.6.1"
      sources."stream-browserify-3.0.0"
      sources."strftime-0.10.0"
      sources."string.prototype.trimend-1.0.4"
      sources."string.prototype.trimstart-1.0.4"
      sources."string_decoder-1.3.0"
      sources."strip-ansi-3.0.1"
      sources."style-loader-0.22.1"
      sources."supports-color-2.0.0"
      sources."tinycon-0.6.8"
      sources."type-2.5.0"
      sources."unbox-primitive-1.0.1"
      sources."uri-js-4.4.1"
      sources."util-0.12.4"
      sources."util-deprecate-1.0.2"
      sources."vue-2.6.14"
      sources."vue-observe-visibility-0.4.6"
      sources."vue-resize-0.4.5"
      sources."vue-virtual-scroller-1.0.10"
      sources."whatwg-fetch-3.6.2"
      sources."which-boxed-primitive-1.0.2"
      sources."which-typed-array-1.1.4"
      sources."xhr-2.6.0"
      sources."xtend-4.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Web based IRC client";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
